name: "CI"

on:
  push:
    branches: [master]
  pull_request:

jobs:
  check:
    name: "Checks and Tests"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      # Yarn equivalent of npm ci.
      - run: yarn install --frozen-lockfile
        shell: bash
      - run: yarn lint
        shell: bash
      - run: yarn test
        shell: bash
